version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Jakarta'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'composer'
      prefix-development: 'composer-dev'
      include: 'scope'
    groups:
      laravel:
        patterns:
          - 'laravel/*'
          - 'illuminate/*'
        update-types:
          - 'minor'
          - 'patch'
      inertia-php:
        patterns:
          - 'inertiajs/*'
        update-types:
          - 'minor'
          - 'patch'
      dev-tools:
        patterns:
          - 'phpunit/*'
          - 'mockery/*'
          - 'fakerphp/*'
          - 'laravel/pint'
          - 'nunomaduro/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'php'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'tuesday'
      time: '09:00'
      timezone: 'Asia/Jakarta'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'npm'
      prefix-development: 'npm-dev'
      include: 'scope'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
        update-types:
          - 'minor'
          - 'patch'
      inertia-react:
        patterns:
          - '@inertiajs/*'
        update-types:
          - 'minor'
          - 'patch'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'laravel-vite-plugin'
        update-types:
          - 'minor'
          - 'patch'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
        update-types:
          - 'minor'
          - 'patch'
      dev-dependencies:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier'
          - 'autoprefixer'
          - 'postcss'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
