services:
  php_comit:
    build: docker/php
    image: php:latest
    container_name: php_comit
    hostname: 'php'
    mem_limit: 2g
    cpus: 1
    volumes:
      - .:/var/www/html
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - mysql_comit

  mysql_comit:
    image: mariadb:10.2
    container_name: mysql_comit
    restart: unless-stopped
    tty: true
    mem_limit: 1.5g
    cpus: 0.75
    ports:
      - '33306:3306'
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: staging
      MYSQL_ROOT_PASSWORD: staging
      TZ: Asia/Jakarta
    read_only: false

  nginx_comit:
    build: docker/nginx
    image: nginx:latest
    container_name: nginx_comit
    hostname: 'nginx'
    mem_limit: 512m
    cpus: 0.25
    ports:
      - '90:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_comit
